---
- hosts: all
  become: yes
  connection: ssh
  tasks:
  - name: Updating apt
    command: sudo apt update
  
  - name: Docker Installation
    apt: name=docker.io update_cache=yes state=latest
  
  - name: Start docker service
    command: sudo systemctl start docker
    become: yes
    become_user: root
  
  - name: Stopping the Docker container 
    command: docker stop insure_me
  
  - name: Removing the Docker container
    command: docker rm -f insure_me

  - name: Removing docker image
    command: docker rmi -f  sam985/insure-me:1.0
      
  - name: Deploying docker container
    command: docker run -itd --name=insure_me  -p 8081:8081 sam985/insure-me:1.0
